services:
  backend:
    container_name: ft-backend-prod 
    image: lordmitrii/ft-backend-prod:latest
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: ft-frontend-prod
    image: lordmitrii/ft-frontend-prod:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    container_name: ft-db-prod
    image: postgres:16
    restart: unless-stopped
    env_file:
    - .env.prod
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

# TODO: remove this in the future once I make admin panel
  pgadmin:
    container_name: ft-pgadmin-prod
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db-data:       

