name: Test and Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dummy test step
        run: echo "Running tests... (no actual tests exist yet)"

  deploy:

    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Backup database
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            export DB_CONTAINER=ft-db-prod
            export POSTGRES_USER=root
            export POSTGRES_DB=fitness_tracker
            BACKUP_DIR=~/fitness-tracker/db_backups
            mkdir -p $BACKUP_DIR
            FILENAME="$BACKUP_DIR/db-backup-latest.sql"
            docker exec -t $DB_CONTAINER pg_dump -U $POSTGRES_USER $POSTGRES_DB > $FILENAME
            echo "DB backup updated: $FILENAME"
      

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ~/fitness-tracker

            git pull origin main
            docker-compose -f docker-compose.prod.yml up -d --build
